services:

  api:
    build: ./api
    ports:
      - 9001:4000
    volumes:
      - ./api/database:/app/database
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - 9000:3000
    env_file:
      - .env
    restart: unless-stopped
